python3 legno_runner.py --search --arco --config configs/extended_naive.cfg cosc
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg micro-osc
#python3 legno_runner.py --search --arco --config configs/extended_naive.cfg vanderpol
#python3 legno_runner.py --search --arco --config configs/extended_naive.cfg lotka
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg pend
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg pend-nl
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg spring
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg spring-nl
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg robot
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg smmrxn
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg rxn-disassoc
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg rxn-dimer
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg rxn-bidir
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg bont
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg epor
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg gentoggle
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg heat1d-g2
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg heat1d-g4
python3 legno_runner.py --search --arco --config configs/extended_naive.cfg heat1d-g8
