CONFIG="standard_naive.cfg"
python3 legno_runner.py --search --arco --config configs/${CONFIG} cosc
python3 legno_runner.py --search --arco --config configs/${CONFIG} micro-osc
python3 legno_runner.py --search --arco --config configs/${CONFIG} vanderpol
python3 legno_runner.py --search --arco --config configs/${CONFIG} lotka
python3 legno_runner.py --search --arco --config configs/${CONFIG} pend
python3 legno_runner.py --search --arco --config configs/${CONFIG} pend-nl
python3 legno_runner.py --search --arco --config configs/${CONFIG} spring
python3 legno_runner.py --search --arco --config configs/${CONFIG} spring-nl
python3 legno_runner.py --search --arco --config configs/${CONFIG} robot
python3 legno_runner.py --search --arco --config configs/${CONFIG} smmrxn
python3 legno_runner.py --search --arco --config configs/${CONFIG} rxn-disassoc
python3 legno_runner.py --search --arco --config configs/${CONFIG} rxn-dimer
python3 legno_runner.py --search --arco --config configs/${CONFIG} rxn-bidir
python3 legno_runner.py --search --arco --config configs/${CONFIG} bont
python3 legno_runner.py --search --arco --config configs/${CONFIG} epor
python3 legno_runner.py --search --arco --config configs/${CONFIG} gentoggle
python3 legno_runner.py --search --arco --config configs/${CONFIG} heat1d-g2
python3 legno_runner.py --search --arco --config configs/${CONFIG} heat1d-g4
python3 legno_runner.py --search --arco --config configs/${CONFIG} heat1d-g8
